### ISSUE TITLE
apt cant find winbox

### ISSUE THREAD

**Issue by hasan4temp** [Vitexus/WinBox.deb#1]
sudo apt update
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://security.debian.org/debian-security bookworm-security InRelease                                                                                                   
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease                                                                                                                  
Hit:4 http://deb.debian.org/debian bookworm-backports InRelease                                                                                                                
Get:5 https://packages.microsoft.com/repos/edge stable InRelease [3,590 B]                                              
Hit:6 https://pkg.cloudflareclient.com bookworm InRelease                                                                           
Ign:7 https://releases.warp.dev/linux/deb stable InRelease                                                       
Hit:8 https://releases.warp.dev/linux/deb stable Release                                                         
Get:9 https://packages.microsoft.com/repos/edge stable/main amd64 Packages [7,866 B]
Get:11 https://pkgs.tailscale.com/stable/debian bookworm InRelease                              
Hit:12 http://repo.vitexsoftware.cz bookworm InRelease        
Fetched 18.0 kB in 2s (7,292 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.

~ via  v18.19.0 took 3s 
❯ sudo apt install winbox
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package winbox

**Comment by Vitexus** [comment]
Thank you for this issue. I found the problem:

```
vitex@pc-vyvoj:~$ sudo apt install winbox
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  winbox
0 upgraded, 1 newly installed, 0 to remove and 18 not upgraded.
Need to get 1 224 kB of archives.
After this operation, 4 177 kB of additional disk space will be used.
Get:1 https://repo.vitexsoftware.com bookworm/games amd64 winbox all 3.40.12~bookworm [1 224 kB]
Fetched 1 224 kB in 0s (17,7 MB/s)   
Selecting previously unselected package winbox.
(Reading database ... 505578 files and directories currently installed.)
Preparing to unpack .../winbox_3.40.12~bookworm_all.deb ...
Unpacking winbox (3.40.12~bookworm) ...
Setting up winbox (3.40.12~bookworm) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for mailcap (3.70+nmu1) ...
```

It will fixed soon

**Comment by Vitexus** [comment]
FIXED 

```
vitex@pc-vyvoj:~$ sudo apt install winbox
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  winbox
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 1 224 kB of archives.
After this operation, 4 177 kB of additional disk space will be used.
Get:1 https://repo.vitexsoftware.com bookworm/main amd64 winbox all 3.40.13~bookworm [1 224 kB]
Fetched 1 224 kB in 0s (17,0 MB/s)   
Selecting previously unselected package winbox.
(Reading database ... 505615 files and directories currently installed.)
Preparing to unpack .../winbox_3.40.13~bookworm_all.deb ...
Unpacking winbox (3.40.13~bookworm) ...
Setting up winbox (3.40.13~bookworm) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for mailcap (3.70+nmu1) ...
```
